version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 761018889186.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t stock-alert .
      - docker tag stock-alert:latest 761018889186.dkr.ecr.eu-north-1.amazonaws.com/stock-alert:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 761018889186.dkr.ecr.eu-north-1.amazonaws.com/stock-alert:latest
      - echo ECS Task will be triggered automatically via EventBridge
